# Generated by Django 3.2.4 on 2021-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taskmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('due', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
