# Generated by Django 3.2.4 on 2021-09-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='completed',
            new_name='status',
        ),
    ]
