# Generated by Django 3.2.4 on 2021-09-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
