# Generated by Django 3.2.4 on 2021-09-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210913_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='status',
        ),
    ]
